### ISSUE TITLE
Can't submit course review for CPSC 110

### ISSUE THREAD

**Issue by lma0305** [ubccsss/ubccsss.org#398]

**Comment by AnimeAllstar** [comment]
Could you elaborate @lma0305

**Comment by lma0305** [comment]
I keep hitting submit, but all it says is "Unable to submit review, Please try again later or check the console for more information"

Then it says if the problem persists, follow the URL to this website.

I've tried hitting resubmit, I've tried refreshing the page and rewriting my review, nothing worked.

**Comment by kewbish** [comment]
Please try again - should be fixed now.

**Comment by lma0305** [comment]
I tried it again, it's still showing the same message

**Comment by AnimeAllstar** [comment]
I just tested it, it should be fixed. If it still doesn't work, try deleting your cache? @lma0305

**Comment by lma0305** [comment]
I tried all of those, and it's still showing me the same message

**Comment by kewbish** [comment]
Please try again! Just debugged some string encoding issues with a special character on the page, apologies for the inconvenience.

**Comment by lma0305** [comment]
Soo... now there's a weird issue where I can submit my review, but I don't see it showing on the review page afterwards.

**Comment by AnimeAllstar** [comment]
@lma0305 course reviews do not show up immediately. They are manually vetted before being published. This is a PR generated for your course review: https://github.com/ubccsss/ubccsss.org/pull/412

**Comment by AnimeAllstar** [comment]
Thanks for writing the review and helping us debug this.
